### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### ISSUE THREAD

**Issue by archonsd** [leplopp/mbm#3]
Got a crash from MBM after I upgraded it from 1.8_1.11.2 to 1.9.0.1_1.11.2 and started an SMP server.  The  crash happened during the SMP server load up.

During the previous game, when I was still running MBM 1.8_1.11.2, I put down an angular wood block successfully.  The orientation was wrong and I did not yet know about the tool to turn them, so I broke the block to move it but I did not get the angular block back.  It disappeared and I lost the resources.  I put another one down, it too was the wrong orientation, so I broke it and did not get it back.  I was concerned about losing all those resources (survival map) so I went to your site and noticed you'd updated it to 1.9.0.1 for MC 1.11.2 so I shut the server down, upgraded the server and client with MBM 1.9.0.1 and restarted the server.  It crashed on load up with the provided trace.

Full crash report:  https://pastebin.com/aEUR2Dak

**Comment by archonsd** [comment]
Found this: https://stackoverflow.com/questions/5218870/getting-a-headlessexception-no-x11-display-variable-was-set, will validate.  But this *is* a headless server.  Is something in 1.9.0.1 client-only and running on a headless SMP server not supported in 1.9.0.1?  (it works fine in 1.8)

**Comment by archonsd** [comment]
Confirmed:  if I execute `export DISPLAY=localhost:0.0` before running the server with MBM 1.9.0.1 installed it does complete load and is joinable.  With 1.8 of MBM you can run the SMP server without the DISPLAY environment variable being set.  As of MBM 1.9.0.1 a headless SMP server has to have DISPLAY set.  I would not think it would be that common to have DISPLAY set for a headless server, but others who see this may save some time finding this workaround now.

**Comment by leplopp** [comment]
new version is available 1.9.0.1A-01

**Comment by archonsd** [comment]
Confirmed -- I unset the DISPLAY variable before relaunching the server running this new revision and the DISPLAY dependency is removed.  Thank you for that.

FWIW, it looks like between the two variants you removed an item?

`[12:49:36] [Server thread/WARN] [FML]: Forge Mod Loader detected missing blocks/items.

There are 1 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
mbm:generator


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
`

Was that intentional?   I didn't have any of them in my world yet, so I just told FML to /confirm.  Server started fine, without the DISPLAY variable being set on a headless server.

**Comment by leplopp** [comment]
I have mbm: generator removed in this version

**Comment by leplopp** [comment]
The item (generator) has been removed in this version
