### ISSUE TITLE
1.9.0.1_1.12 crashes dedicated server Forge 1.12 build 2400

### ISSUE THREAD

**Issue by kreezxil** [leplopp/mbm#5]
Notes:
     on startup

crash report:
https://gist.github.com/7909a2aa05d35f5605bd4b5a422dfaa9

fml server latest:
https://gist.github.com/cbc23a2809cf628731fdeb95bff9ed71

**Comment by leplopp** [comment]
the minimum forge version is 2344

in the next update is forge 2397
