### ISSUE TITLE
Client crash on start:  mbm-Master_Blocks_Mod v.1.9.0.3_1.11.2.jar

### ISSUE THREAD

**Issue by archonsd** [leplopp/mbm#7]
MC 1.11.2 client with Forge 2393 and MBM 1.9.0.3 crashing on startup 100% of the time.  Exception in MBM.  Did not happen on 1.9.0.1A.

https://pastebin.com/9Ghf52wU

**Comment by leplopp** [comment]
new version 1.9.0.3-01 1.11.2
