### ISSUE TITLE
crash on server startup(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [leplopp/mbm#9]
Forge:1.12-2413
MBM: mbm-Master_Blocks_Mod_1.9.0.3_1.12

crash report:
[crash-2017-07-18_18.18.05-server.txt](https://github.com/leplopp/mbm/files/1155133/crash-2017-07-18_18.18.05-server.txt)

**Comment by leplopp** [comment]
oh sorry for this  i have made the registry for the client 

here is a new update for 1.12 server =:

[](https://minecraft.curseforge.com/projects/master-blocks-mod/files/2452513)

**Comment by CrankySupertoon** [comment]
ps @SDUBZ the 1.10.2 versions has a registry error too

**Comment by leplopp** [comment]
@CrankySupertoon 
i have the 1.10.2 version with my mod tested 

the 1.10.2 server is no crashed 
and has no registry error
